### ISSUE TITLE
Issue with missing Nomen SES file

### ISSUE THREAD

**Issue by MetadataKate** [iflastandards/iflastandards.info#12]
I found an issue on the web page at https://www.iflastandards.info/ISBDM/docs/ves/. There is no https://www.iflastandards.info/ISBDM/docs/ves/ISBDMSESNom.html page to link the 3 SES pages underneath too. See attached file
![ISBDM values toc screenshot](https://github.com/iflastandards/iflastandards.info/assets/138510380/e475b5d4-a946-4da0-9e85-903d6914c42e)

There is some standard language about source files provided in this feedback form. However, there is no https://github.com/iflastandards/iflastandards.info/blob/master/docs/_pages/ISBDM/docs/ves/ISBDMSESNom.html file either so I don't know how to provide you with the appropriate links. I got here from the Feedback link on the ISBDM page.

**Comment by GordonDunsire** [comment]
This is intentional. A nomen is any kind of string that is used to refer to a specific instance of any other entity. There cannot, therefore, be a general string encoding scheme (SES) for the Nomen entity. The unlinked entry is a gathering device for the three specific kinds of nomen that do have SES pages. We will consider adding a typographic device (e.g. italics or square brackets) to clarify this.

**Comment by josephhafner** [comment]
[like]  Joseph Hafner reacted to your message:
________________________________

**Comment by josephhafner** [comment]
[like]  Joseph Hafner reacted to your message:
________________________________
